#!/usr/bin/env python3
"""Pre-render Mini App routes to HTML (один запрос, без fetch и marked в WebView)."""
from __future__ import annotations

import html
import json
import re
from pathlib import Path

try:
    import markdown
except ImportError as exc:
    raise SystemExit(
        "Install markdown: pip install markdown && python scripts/build_miniapp_bundle.py"
    ) from exc

ROOT = Path(__file__).resolve().parents[1]
DOCS = ROOT / "docs" / "documents"
OUT = ROOT / "docs" / "miniapp" / "embedded_html.js"

ROUTE_FILES: dict[str, str] = {
    "legal:terms": "public_offer.md",
    "legal:privacy": "policy_personal.md",
    "legal:consent": "consent_personal.md",
    "models": "models_guide.md",
    "quality": "quality_guide.md",
}


def md_to_html(text: str) -> str:
    body = markdown.markdown(
        text,
        extensions=["extra", "sane_lists", "nl2br"],
        output_format="html5",
    )
    return f'<div class="doc-md">{body}</div>'


def extract_title(text: str) -> str:
    for line in text.splitlines():
        line = line.strip()
        if line.startswith("# "):
            return line[2:].strip()
    return "StyleGenie"


def main() -> None:
    routes: dict[str, dict[str, str]] = {}
    for route, filename in ROUTE_FILES.items():
        path = DOCS / filename
        if not path.is_file():
            raise SystemExit(f"Missing {path}")
        raw = path.read_text(encoding="utf-8")
        routes[route] = {
            "title": extract_title(raw),
            "html": md_to_html(raw),
        }

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(
        "// Auto-generated by scripts/build_miniapp_bundle.py\n"
        "(function (g) {\n"
        f"  g.__SG_ROUTES__ = {json.dumps(routes, ensure_ascii=False)};\n"
        "})(window);\n",
        encoding="utf-8",
    )
    print(f"Wrote {OUT} ({OUT.stat().st_size} bytes, {len(routes)} routes)")


if __name__ == "__main__":
    main()
